import logging
import os
import re
from cachetools import TTLCache
from fastapi import FastAPI, Request, Response
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import HTMLResponse, PlainTextResponse, StreamingResponse
from openai import AsyncOpenAI
from slowapi import Limiter
from slowapi.util import get_remote_address
from slowapi.errors import RateLimitExceeded

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
log = logging.getLogger(__name__)

client = AsyncOpenAI(
    base_url="https://openrouter.ai/api/v1",
    api_key=os.environ.get("OPENROUTER_API_KEY", ""),
)

MODEL = os.environ.get("MODEL", "openrouter/free")
RATE_LIMIT = os.environ.get("RATE_LIMIT", "10/minute")
CACHE_TTL = int(os.environ.get("CACHE_TTL", "600"))
ALLOWED_ORIGINS = [
    "https://ephemeral-wiki.onrender.com",
]

cache: TTLCache = TTLCache(maxsize=256, ttl=CACHE_TTL)

app = FastAPI(docs_url=None, redoc_url=None, openapi_url=None)
limiter = Limiter(key_func=get_remote_address)
app.state.limiter = limiter


@app.exception_handler(RateLimitExceeded)
async def rate_limit_handler(request: Request, exc: RateLimitExceeded):
    return HTMLResponse(
        content=ERROR_PAGE.format(
            title="Rate Limited",
            message="Too many requests. Please wait a moment and try again.",
        ),
        status_code=429,
    )


app.add_middleware(
    CORSMiddleware,
    allow_origins=ALLOWED_ORIGINS,
    allow_methods=["GET"],
    allow_headers=["*"],
)


@app.middleware("http")
async def security_headers(request: Request, call_next):
    response = await call_next(request)
    response.headers["X-Content-Type-Options"] = "nosniff"
    response.headers["X-Frame-Options"] = "DENY"
    response.headers["Referrer-Policy"] = "strict-origin-when-cross-origin"
    response.headers["Permissions-Policy"] = "geolocation=(), camera=(), microphone=()"
    return response


SYSTEM_PROMPT = (
    "You are Ephemeral Wiki, a website where every page is generated on-the-fly by AI. "
    "Your output is served directly as a web page. "
    "Output ONLY raw HTML. NEVER wrap output in ```html``` code fences or markdown formatting. "
    "The very first character of your response must be '<'. "
    "Generate a complete, self-contained HTML document with inline CSS styling. "
    "Include a <head> with a descriptive <title> and a <meta charset='utf-8'>. "
    "Use clean, readable typography and a pleasant color scheme. "
    "Include relative <a href> links to related topics so users can explore. "
    "At the bottom, include a small footer noting this page was generated by AI and is not authoritative."
)

HOME_PROMPT = (
    "Generate the home page for Ephemeral Wiki. Explain that every page on this site "
    "is generated by AI on each visit and only exists while being viewed. "
    "Users can navigate to any URL path to get a page about that topic. "
    "Include a list of example links to interesting topics. "
    "Note the site is rate-limited to prevent abuse."
)

ERROR_PAGE = """<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>{title}</title>
<style>
body {{ font-family: system-ui, sans-serif; max-width: 600px; margin: 80px auto; padding: 0 20px; color: #333; }}
h1 {{ color: #c00; }}
</style></head>
<body><h1>{title}</h1><p>{message}</p><p><a href="/">Back to home</a></p></body></html>"""

STATIC_PATHS = {"favicon.ico", "apple-touch-icon.png", "apple-touch-icon-precomposed.png"}


def build_prompt(path: str) -> str:
    if path in ("", "/", "index.html", "/index.html"):
        return HOME_PROMPT
    readable = path.replace("/", " > ").replace("-", " ").replace("_", " ").strip()
    return f"Generate an HTML page about: {readable}\nURL path: /{path}"


def strip_fences(html: str) -> str:
    html = re.sub(r"^```(?:html)?\s*\n?", "", html)
    html = re.sub(r"\n?```\s*$", "", html)
    return html


async def generate_stream(path: str):
    prompt = build_prompt(path)
    try:
        stream = await client.chat.completions.create(
            model=MODEL,
            messages=[
                {"role": "system", "content": SYSTEM_PROMPT},
                {"role": "user", "content": prompt},
            ],
            max_tokens=4096,
            stream=True,
        )
        buffer = []
        streaming = False
        async for chunk in stream:
            if chunk.choices and chunk.choices[0].delta.content:
                text = chunk.choices[0].delta.content
                if not streaming:
                    buffer.append(text)
                    joined = "".join(buffer)
                    idx = joined.find("<")
                    if idx != -1:
                        streaming = True
                        yield joined[idx:]
                else:
                    buffer.append(text)
                    yield text
        full = strip_fences("".join(buffer))
        cache[path] = full
        log.info("Generated page for /%s", path)
    except Exception as e:
        log.error("Generation failed for /%s: %s", path, e)
        yield ERROR_PAGE.format(
            title="Generation Failed",
            message="Something went wrong while generating this page. Please try again.",
        )


@app.get("/healthz")
async def healthz():
    return PlainTextResponse("ok")


@app.get("/robots.txt")
async def robots():
    return PlainTextResponse("User-agent: *\nDisallow: /\nAllow: /$\n")


@app.get("/{path:path}")
@limiter.limit(RATE_LIMIT)
async def catch_all(request: Request, path: str = ""):
    if path in STATIC_PATHS:
        return Response(status_code=404)

    cached = cache.get(path)
    if cached:
        log.info("Cache hit for /%s", path)
        return HTMLResponse(content=cached)

    return StreamingResponse(
        generate_stream(path),
        media_type="text/html",
    )
